[build]
    base = "web/"
    publish = "dist"
    command = "npm install && npm run build && ls -laR dist/"
    ignore = "git diff --quiet HEAD^ HEAD -- ."

[build.environment]
    YARN_FLAGS = "--no-ignore-optional"
    API_URL = "https://yolo.berty.io/api"
    SERVER_URL = "https://yolo.berty.io"

[context.production.environment]
    API_URL = "https://yolo.berty.io/api"
    SERVER_URL = "https://yolo.berty.io"
