[build]
    base = "web/"
    publish = "build"
    command = "yarn install && yarn build && ls -laR build/"
    ignore = "git diff --quiet HEAD^ HEAD -- ."

[build.environment]
    YARN_FLAGS = "--no-ignore-optional"
    REACT_APP_API_SERVER = "https://yolo.berty.io"

[context.production.environment]
    REACT_APP_API_SERVER = "https://yolo.berty.io"
